package xyz.mek030399.tokenflow.data

import android.content.Context
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.ColumnInfo
import androidx.room.Query
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.room.Transaction
import androidx.room.Upsert
import androidx.sqlite.db.SupportSQLiteDatabase

@Entity(tableName = "providers")
data class ProviderEntity(
    @androidx.room.PrimaryKey val id: String,
    val name: String,
    val baseUrl: String,
    val protocol: String,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(
    tableName = "models",
    foreignKeys = [ForeignKey(
        entity = ProviderEntity::class,
        parentColumns = ["id"],
        childColumns = ["providerId"],
        onDelete = ForeignKey.CASCADE,
    )],
    indices = [Index("providerId"), Index(value = ["providerId", "remoteId"])],
)
data class ModelEntity(
    @androidx.room.PrimaryKey val id: String,
    val providerId: String,
    val remoteId: String,
    val displayName: String,
    val maxOutputTokens: Int,
    val isDefault: Boolean,
    @ColumnInfo(defaultValue = "'UNKNOWN'") val visionStatus: String,
    val visionCheckedAt: Long?,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(
    tableName = "conversations",
    foreignKeys = [ForeignKey(
        entity = ModelEntity::class,
        parentColumns = ["id"],
        childColumns = ["modelId"],
        onDelete = ForeignKey.SET_NULL,
    )],
    indices = [Index("modelId"), Index("updatedAt")],
)
data class ConversationEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val titleAutoGenerated: Boolean,
    val modelId: String?,
    @ColumnInfo(defaultValue = "'OVERRIDE'") val modelMode: String,
    val modelOverrideId: String?,
    val thinkingEffort: String,
    val systemPrompt: String,
    @ColumnInfo(defaultValue = "'OVERRIDE'") val systemPromptMode: String,
    val nickname: String,
    val userAvatar: String,
    @ColumnInfo(defaultValue = "'INHERIT'") val userAvatarMode: String,
    val assistantAvatar: String,
    @ColumnInfo(defaultValue = "'INHERIT'") val assistantAvatarMode: String,
    val urlReaderBackend: String?,
    val maxToolCalls: Int,
    @ColumnInfo(defaultValue = "1") val enableSearch: Boolean,
    @ColumnInfo(defaultValue = "1") val enableRead: Boolean,
    @ColumnInfo(defaultValue = "0") val enableKnowledge: Boolean,
    val pinnedAt: Long?,
    val archivedAt: Long?,
    val branchedFromConversationId: String?,
    val branchedFromMessageId: String?,
    val status: String,
    val statusMessage: String,
    val createdAt: Long,
    val updatedAt: Long,
    val lastMessageAt: Long?,
)

@Entity(tableName = "app_settings")
data class AppSettingsEntity(
    @androidx.room.PrimaryKey val id: Int = SINGLETON_ID,
    val systemPrompt: String = "",
    val userAvatar: String = "U",
    val assistantAvatar: String = "AI",
    val urlReaderBackend: String = UrlReaderBackend.BUILT_IN.name,
    val visionFallbackModelId: String? = null,
    @ColumnInfo(defaultValue = "'mimo_default'") val mimoTtsVoice: String = "mimo_default",
    @ColumnInfo(defaultValue = "'一念无限'") val assistantNickname: String = DEFAULT_ASSISTANT_NICKNAME,
) {
    companion object {
        const val SINGLETON_ID = 1
    }
}

@Entity(
    tableName = "messages",
    foreignKeys = [ForeignKey(
        entity = ConversationEntity::class,
        parentColumns = ["id"],
        childColumns = ["conversationId"],
        onDelete = ForeignKey.CASCADE,
    )],
    indices = [Index("conversationId"), Index(value = ["conversationId", "createdAt"])],
)
data class MessageEntity(
    @androidx.room.PrimaryKey val id: String,
    val conversationId: String,
    val parentMessageId: String?,
    val requestId: String,
    val role: String,
    val content: String,
    val metadata: String,
    val status: String,
    val createdAt: Long,
)

@Entity(
    tableName = "message_attachments",
    foreignKeys = [ForeignKey(
        entity = MessageEntity::class,
        parentColumns = ["id"],
        childColumns = ["messageId"],
        onDelete = ForeignKey.CASCADE,
    )],
    indices = [Index("messageId"), Index(value = ["messageId", "createdAt"])],
)
data class MessageAttachmentEntity(
    @androidx.room.PrimaryKey val id: String,
    val messageId: String,
    val fileName: String,
    val mimeType: String,
    val kind: String,
    val storedPath: String,
    val sizeBytes: Long,
    val extractedText: String,
    val status: String,
    val width: Int?,
    val height: Int?,
    val createdAt: Long,
)

@Entity(
    tableName = "bookmarks",
    foreignKeys = [ForeignKey(
        entity = MessageEntity::class,
        parentColumns = ["id"],
        childColumns = ["messageId"],
        onDelete = ForeignKey.CASCADE,
    )],
    indices = [Index(value = ["messageId"], unique = true), Index("createdAt")],
)
data class BookmarkEntity(
    @androidx.room.PrimaryKey val id: String,
    val messageId: String,
    val createdAt: Long,
)

@Entity(tableName = "notes", indices = [Index("updatedAt"), Index(value = ["sourceMessageId"], unique = true)])
data class NoteEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val body: String,
    val sourceMessageId: String?,
    val sourceConversationId: String?,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(
    tableName = "agents",
    foreignKeys = [ForeignKey(
        entity = ModelEntity::class,
        parentColumns = ["id"],
        childColumns = ["modelId"],
        onDelete = ForeignKey.SET_NULL,
    )],
    indices = [Index("modelId"), Index("updatedAt")],
)
data class AgentEntity(
    @androidx.room.PrimaryKey val id: String,
    val name: String,
    val description: String,
    val modelId: String?,
    val systemPrompt: String,
    val thinkingEffort: String,
    val maxToolCalls: Int,
    val enableSearch: Boolean,
    val enableRead: Boolean,
    val enableKnowledge: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
)

@Entity(
    tableName = "knowledge_documents",
    indices = [Index("updatedAt"), Index(value = ["sourceNoteId"], unique = true)],
)
data class KnowledgeDocumentEntity(
    @androidx.room.PrimaryKey val id: String,
    val name: String,
    val mimeType: String,
    val storedPath: String,
    val sizeBytes: Long,
    val status: String,
    val error: String,
    val chunkCount: Int,
    val createdAt: Long,
    val updatedAt: Long,
    val sourceNoteId: String? = null,
)

@Entity(
    tableName = "knowledge_chunks",
    foreignKeys = [ForeignKey(
        entity = KnowledgeDocumentEntity::class,
        parentColumns = ["id"],
        childColumns = ["documentId"],
        onDelete = ForeignKey.CASCADE,
    )],
    indices = [Index("documentId"), Index(value = ["documentId", "position"], unique = true)],
)
data class KnowledgeChunkEntity(
    @androidx.room.PrimaryKey(autoGenerate = true) val id: Long = 0,
    val documentId: String,
    val position: Int,
    val text: String,
    val searchText: String,
)

@Fts4
@Entity(tableName = "knowledge_chunks_fts")
data class KnowledgeChunkFts(
    val documentId: String,
    val searchText: String,
)

@Dao
interface LocalDao {
    @Query("SELECT * FROM app_settings WHERE id = 1")
    suspend fun appSettings(): AppSettingsEntity?

    @Upsert
    suspend fun putAppSettings(settings: AppSettingsEntity)

    @Query("SELECT * FROM providers ORDER BY name COLLATE NOCASE, createdAt")
    suspend fun providers(): List<ProviderEntity>

    @Query("SELECT * FROM providers WHERE id = :id")
    suspend fun provider(id: String): ProviderEntity?

    @Upsert
    suspend fun putProvider(provider: ProviderEntity)

    @Upsert
    suspend fun putProviders(providers: List<ProviderEntity>)

    @Query("DELETE FROM providers WHERE id = :id")
    suspend fun deleteProvider(id: String)

    @Query("SELECT * FROM models ORDER BY isDefault DESC, displayName COLLATE NOCASE, createdAt")
    suspend fun models(): List<ModelEntity>

    @Query("SELECT * FROM models WHERE providerId = :providerId ORDER BY displayName COLLATE NOCASE")
    suspend fun modelsForProvider(providerId: String): List<ModelEntity>

    @Query("SELECT * FROM models WHERE id = :id")
    suspend fun model(id: String): ModelEntity?

    @Query("UPDATE models SET visionStatus = :status, visionCheckedAt = :checkedAt WHERE id = :id")
    suspend fun updateVisionStatus(id: String, status: String, checkedAt: Long?)

    @Query("SELECT * FROM models WHERE isDefault = 1 ORDER BY updatedAt DESC LIMIT 1")
    suspend fun defaultModel(): ModelEntity?

    @Upsert
    suspend fun putModels(models: List<ModelEntity>)

    @Query("DELETE FROM models WHERE providerId = :providerId AND id NOT IN (:keepIds)")
    suspend fun deleteOtherProviderModels(providerId: String, keepIds: List<String>)

    @Query("DELETE FROM models WHERE providerId = :providerId")
    suspend fun deleteAllProviderModels(providerId: String)

    @Query("UPDATE models SET isDefault = CASE WHEN id = :id THEN 1 ELSE 0 END")
    suspend fun setDefaultModel(id: String)

    @Transaction
    suspend fun setGlobalDefaultModel(id: String) {
        setDefaultModel(id)
    }

    @Query("SELECT * FROM conversations ORDER BY (pinnedAt IS NOT NULL) DESC, pinnedAt DESC, COALESCE(lastMessageAt, updatedAt) DESC")
    suspend fun conversations(): List<ConversationEntity>

    @Query("SELECT * FROM conversations WHERE id = :id")
    suspend fun conversation(id: String): ConversationEntity?

    @Upsert
    suspend fun putConversation(conversation: ConversationEntity)

    @Query("DELETE FROM conversations WHERE id = :id")
    suspend fun deleteConversation(id: String)

    @Query("DELETE FROM conversations WHERE id IN (:ids)")
    suspend fun deleteConversations(ids: List<String>)

    @Query("SELECT * FROM messages WHERE conversationId = :conversationId ORDER BY createdAt, id")
    suspend fun messages(conversationId: String): List<MessageEntity>

    @Query("SELECT * FROM message_attachments WHERE messageId IN (:messageIds) ORDER BY createdAt, id")
    suspend fun attachmentsForMessages(messageIds: List<String>): List<MessageAttachmentEntity>

    @Query("SELECT * FROM message_attachments WHERE messageId = :messageId ORDER BY createdAt, id")
    suspend fun attachmentsForMessage(messageId: String): List<MessageAttachmentEntity>

    @Upsert
    suspend fun putAttachments(attachments: List<MessageAttachmentEntity>)

    @Query("SELECT * FROM messages WHERE id = :id")
    suspend fun message(id: String): MessageEntity?

    @Query("SELECT * FROM messages WHERE conversationId = :conversationId AND role = 'assistant' ORDER BY createdAt DESC, id DESC LIMIT 1")
    suspend fun latestAssistant(conversationId: String): MessageEntity?

    @Upsert
    suspend fun putMessages(messages: List<MessageEntity>)

    @Transaction
    suspend fun putBranch(
        conversation: ConversationEntity,
        messages: List<MessageEntity>,
        attachments: List<MessageAttachmentEntity>,
    ) {
        putConversation(conversation)
        putMessages(messages)
        if (attachments.isNotEmpty()) putAttachments(attachments)
    }

    @Query("DELETE FROM messages WHERE id = :id")
    suspend fun deleteMessage(id: String)

    @Query("SELECT * FROM messages WHERE status = 'generating'")
    suspend fun generatingMessages(): List<MessageEntity>

    @Query("UPDATE conversations SET status = 'idle', statusMessage = '' WHERE status = 'generating'")
    suspend fun interruptGeneratingConversations()

    @Query("SELECT * FROM bookmarks ORDER BY createdAt DESC")
    suspend fun bookmarks(): List<BookmarkEntity>

    @Query("SELECT * FROM bookmarks WHERE messageId = :messageId LIMIT 1")
    suspend fun bookmarkForMessage(messageId: String): BookmarkEntity?

    @Upsert
    suspend fun putBookmark(bookmark: BookmarkEntity)

    @Query("DELETE FROM bookmarks WHERE messageId = :messageId")
    suspend fun deleteBookmarkForMessage(messageId: String)

    @Query("DELETE FROM bookmarks WHERE messageId IN (:messageIds)")
    suspend fun deleteBookmarks(messageIds: Set<String>)

    @Query("SELECT * FROM notes ORDER BY updatedAt DESC")
    suspend fun notes(): List<NoteEntity>

    @Query("SELECT * FROM notes WHERE id = :id")
    suspend fun note(id: String): NoteEntity?

    @Query("SELECT * FROM notes WHERE sourceMessageId = :messageId LIMIT 1")
    suspend fun noteForSourceMessage(messageId: String): NoteEntity?

    @Upsert
    suspend fun putNote(note: NoteEntity)

    @Query(
        """
        UPDATE notes
        SET title = :newTitle, body = :newBody, updatedAt = :newUpdatedAt
        WHERE id = :id
          AND title = :expectedTitle
          AND body = :expectedBody
          AND updatedAt = :expectedUpdatedAt
        """,
    )
    suspend fun updateNoteIfUnchanged(
        id: String,
        expectedTitle: String,
        expectedBody: String,
        expectedUpdatedAt: Long,
        newTitle: String,
        newBody: String,
        newUpdatedAt: Long,
    ): Int

    @Transaction
    suspend fun putNoteIfSourceAbsent(note: NoteEntity): NoteEntity {
        val sourceMessageId = note.sourceMessageId
        val existing = sourceMessageId?.let { noteForSourceMessage(it) }
        if (existing != null && existing.id != note.id) return existing
        putNote(note)
        return note
    }

    @Query("DELETE FROM notes WHERE id = :id")
    suspend fun deleteNote(id: String)

    @Query("DELETE FROM notes WHERE id IN (:ids)")
    suspend fun deleteNotes(ids: Set<String>)

    @Query("SELECT * FROM agents ORDER BY updatedAt DESC")
    suspend fun agents(): List<AgentEntity>

    @Query("SELECT * FROM agents WHERE id = :id")
    suspend fun agent(id: String): AgentEntity?

    @Upsert
    suspend fun putAgent(agent: AgentEntity)

    @Upsert
    suspend fun putAgents(agents: List<AgentEntity>)

    @Query("DELETE FROM agents WHERE id = :id")
    suspend fun deleteAgent(id: String)

    @Query("SELECT * FROM knowledge_documents ORDER BY updatedAt DESC")
    suspend fun knowledgeDocuments(): List<KnowledgeDocumentEntity>

    @Query("SELECT * FROM knowledge_documents WHERE id = :id")
    suspend fun knowledgeDocument(id: String): KnowledgeDocumentEntity?

    @Query("SELECT * FROM knowledge_documents WHERE sourceNoteId = :sourceNoteId LIMIT 1")
    suspend fun knowledgeDocumentForSourceNote(sourceNoteId: String): KnowledgeDocumentEntity?

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertKnowledgeDocument(document: KnowledgeDocumentEntity): Long

    @Upsert
    suspend fun putKnowledgeDocument(document: KnowledgeDocumentEntity)

    @Query("DELETE FROM knowledge_documents WHERE id = :id")
    suspend fun deleteKnowledgeDocument(id: String)

    @Query("UPDATE knowledge_documents SET status = 'error', error = 'Indexing was interrupted', updatedAt = :now WHERE status = 'indexing'")
    suspend fun interruptKnowledgeIndexing(now: Long)

    @Insert
    suspend fun insertKnowledgeChunk(chunk: KnowledgeChunkEntity): Long

    @Query("SELECT * FROM knowledge_chunks WHERE id IN (:ids)")
    suspend fun knowledgeChunks(ids: List<Long>): List<KnowledgeChunkEntity>

    @Query("SELECT * FROM knowledge_chunks WHERE documentId = :documentId ORDER BY position")
    suspend fun knowledgeChunksForDocument(documentId: String): List<KnowledgeChunkEntity>

    @Query("INSERT INTO knowledge_chunks_fts(rowid, documentId, searchText) VALUES(:rowId, :documentId, :searchText)")
    suspend fun insertKnowledgeFts(rowId: Long, documentId: String, searchText: String)

    @Query("DELETE FROM knowledge_chunks_fts WHERE documentId = :documentId")
    suspend fun deleteKnowledgeFts(documentId: String)

    @Query("DELETE FROM knowledge_chunks WHERE documentId = :documentId")
    suspend fun deleteKnowledgeChunks(documentId: String)

    @Query("SELECT kc.* FROM knowledge_chunks kc JOIN knowledge_chunks_fts fts ON fts.rowid = kc.id WHERE knowledge_chunks_fts MATCH :query LIMIT :limit")
    suspend fun searchKnowledgeChunks(query: String, limit: Int): List<KnowledgeChunkEntity>

    @Transaction
    suspend fun replaceKnowledgeChunks(documentId: String, chunks: List<KnowledgeChunkEntity>) {
        deleteKnowledgeFts(documentId)
        deleteKnowledgeChunks(documentId)
        chunks.forEach { chunk ->
            val rowId = insertKnowledgeChunk(chunk)
            insertKnowledgeFts(rowId, documentId, chunk.searchText)
        }
    }

    @Transaction
    suspend fun replaceProviderModels(providerId: String, models: List<ModelEntity>) {
        putModels(models)
        if (models.isEmpty()) deleteAllProviderModels(providerId)
        else deleteOtherProviderModels(providerId, models.map { it.id })
    }

    @Transaction
    suspend fun saveProviderWithModels(provider: ProviderEntity, models: List<ModelEntity>) {
        putProvider(provider)
        replaceProviderModels(provider.id, models)
    }

    @Transaction
    suspend fun mergeConfiguration(
        providers: List<ProviderEntity>,
        models: List<ModelEntity>,
        defaultModelId: String?,
        settings: AppSettingsEntity? = null,
        agents: List<AgentEntity> = emptyList(),
    ) {
        putProviders(providers)
        putModels(models)
        defaultModelId?.let { setDefaultModel(it) }
        settings?.let { putAppSettings(it) }
        if (agents.isNotEmpty()) putAgents(agents)
    }
}

@Database(
    entities = [
        ProviderEntity::class,
        ModelEntity::class,
        ConversationEntity::class,
        MessageEntity::class,
        MessageAttachmentEntity::class,
        AppSettingsEntity::class,
        BookmarkEntity::class,
        NoteEntity::class,
        AgentEntity::class,
        KnowledgeDocumentEntity::class,
        KnowledgeChunkEntity::class,
        KnowledgeChunkFts::class,
    ],
    version = 6,
    exportSchema = true,
)
abstract class TokenFlowDatabase : RoomDatabase() {
    abstract fun localDao(): LocalDao

    companion object {
        fun open(context: Context): TokenFlowDatabase = Room.databaseBuilder(
            context.applicationContext,
            TokenFlowDatabase::class.java,
            "tokenflow-local.db",
        ).addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6).build()

        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """CREATE TABLE IF NOT EXISTS `app_settings` (
                        `id` INTEGER NOT NULL,
                        `systemPrompt` TEXT NOT NULL,
                        `userAvatar` TEXT NOT NULL,
                        `assistantAvatar` TEXT NOT NULL,
                        `urlReaderBackend` TEXT NOT NULL,
                        PRIMARY KEY(`id`)
                    )""".trimIndent(),
                )
                db.execSQL(
                    "INSERT OR IGNORE INTO app_settings(id, systemPrompt, userAvatar, assistantAvatar, urlReaderBackend) " +
                        "VALUES(1, '', 'U', 'AI', 'BUILT_IN')",
                )
                db.execSQL("ALTER TABLE conversations ADD COLUMN modelMode TEXT NOT NULL DEFAULT 'OVERRIDE'")
                db.execSQL("ALTER TABLE conversations ADD COLUMN modelOverrideId TEXT")
                db.execSQL("ALTER TABLE conversations ADD COLUMN systemPromptMode TEXT NOT NULL DEFAULT 'OVERRIDE'")
                db.execSQL("ALTER TABLE conversations ADD COLUMN userAvatarMode TEXT NOT NULL DEFAULT 'INHERIT'")
                db.execSQL("ALTER TABLE conversations ADD COLUMN assistantAvatarMode TEXT NOT NULL DEFAULT 'INHERIT'")
                db.execSQL("ALTER TABLE conversations ADD COLUMN urlReaderBackend TEXT")
                db.execSQL("UPDATE conversations SET modelOverrideId = modelId")
                db.execSQL(
                    """UPDATE conversations
                        SET modelMode = 'INHERIT', modelOverrideId = NULL
                        WHERE modelId = (SELECT id FROM models WHERE isDefault = 1 ORDER BY updatedAt DESC LIMIT 1)
                    """.trimIndent(),
                )
                db.execSQL("UPDATE conversations SET systemPromptMode = 'INHERIT' WHERE TRIM(systemPrompt) = ''")
            }
        }

        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE conversations ADD COLUMN enableSearch INTEGER NOT NULL DEFAULT 1")
                db.execSQL("ALTER TABLE conversations ADD COLUMN enableRead INTEGER NOT NULL DEFAULT 1")
                db.execSQL("ALTER TABLE conversations ADD COLUMN enableKnowledge INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE conversations ADD COLUMN pinnedAt INTEGER")
                db.execSQL("ALTER TABLE conversations ADD COLUMN archivedAt INTEGER")
                db.execSQL("CREATE TABLE IF NOT EXISTS bookmarks (id TEXT NOT NULL, messageId TEXT NOT NULL, createdAt INTEGER NOT NULL, PRIMARY KEY(id), FOREIGN KEY(messageId) REFERENCES messages(id) ON UPDATE NO ACTION ON DELETE CASCADE)")
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_bookmarks_messageId ON bookmarks(messageId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_bookmarks_createdAt ON bookmarks(createdAt)")
                db.execSQL("CREATE TABLE IF NOT EXISTS notes (id TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, sourceMessageId TEXT, sourceConversationId TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, PRIMARY KEY(id))")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_notes_updatedAt ON notes(updatedAt)")
                db.execSQL("CREATE TABLE IF NOT EXISTS agents (id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, modelId TEXT, systemPrompt TEXT NOT NULL, thinkingEffort TEXT NOT NULL, maxToolCalls INTEGER NOT NULL, enableSearch INTEGER NOT NULL, enableRead INTEGER NOT NULL, enableKnowledge INTEGER NOT NULL, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, PRIMARY KEY(id), FOREIGN KEY(modelId) REFERENCES models(id) ON UPDATE NO ACTION ON DELETE SET NULL)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_agents_modelId ON agents(modelId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_agents_updatedAt ON agents(updatedAt)")
                db.execSQL("CREATE TABLE IF NOT EXISTS knowledge_documents (id TEXT NOT NULL, name TEXT NOT NULL, mimeType TEXT NOT NULL, storedPath TEXT NOT NULL, sizeBytes INTEGER NOT NULL, status TEXT NOT NULL, error TEXT NOT NULL, chunkCount INTEGER NOT NULL, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, PRIMARY KEY(id))")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_knowledge_documents_updatedAt ON knowledge_documents(updatedAt)")
                db.execSQL("CREATE TABLE IF NOT EXISTS knowledge_chunks (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, documentId TEXT NOT NULL, position INTEGER NOT NULL, text TEXT NOT NULL, searchText TEXT NOT NULL, FOREIGN KEY(documentId) REFERENCES knowledge_documents(id) ON UPDATE NO ACTION ON DELETE CASCADE)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_knowledge_chunks_documentId ON knowledge_chunks(documentId)")
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_knowledge_chunks_documentId_position ON knowledge_chunks(documentId, position)")
                db.execSQL("CREATE VIRTUAL TABLE IF NOT EXISTS knowledge_chunks_fts USING FTS4(documentId TEXT NOT NULL, searchText TEXT NOT NULL)")
            }
        }

        val MIGRATION_3_4 = object : Migration(3, 4) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE models ADD COLUMN visionStatus TEXT NOT NULL DEFAULT 'UNKNOWN'")
                db.execSQL("ALTER TABLE models ADD COLUMN visionCheckedAt INTEGER")
                db.execSQL("ALTER TABLE app_settings ADD COLUMN visionFallbackModelId TEXT")
                db.execSQL("ALTER TABLE app_settings ADD COLUMN mimoTtsVoice TEXT NOT NULL DEFAULT 'mimo_default'")
                db.execSQL("ALTER TABLE conversations ADD COLUMN branchedFromConversationId TEXT")
                db.execSQL("ALTER TABLE conversations ADD COLUMN branchedFromMessageId TEXT")
                db.execSQL(
                    """CREATE TABLE IF NOT EXISTS message_attachments (
                        id TEXT NOT NULL,
                        messageId TEXT NOT NULL,
                        fileName TEXT NOT NULL,
                        mimeType TEXT NOT NULL,
                        kind TEXT NOT NULL,
                        storedPath TEXT NOT NULL,
                        sizeBytes INTEGER NOT NULL,
                        extractedText TEXT NOT NULL,
                        status TEXT NOT NULL,
                        width INTEGER,
                        height INTEGER,
                        createdAt INTEGER NOT NULL,
                        PRIMARY KEY(id),
                        FOREIGN KEY(messageId) REFERENCES messages(id) ON UPDATE NO ACTION ON DELETE CASCADE
                    )""".trimIndent(),
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS index_message_attachments_messageId ON message_attachments(messageId)")
                db.execSQL("CREATE INDEX IF NOT EXISTS index_message_attachments_messageId_createdAt ON message_attachments(messageId, createdAt)")
                db.execSQL("DELETE FROM notes WHERE sourceMessageId IS NOT NULL AND rowid NOT IN (SELECT MIN(rowid) FROM notes WHERE sourceMessageId IS NOT NULL GROUP BY sourceMessageId)")
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_notes_sourceMessageId ON notes(sourceMessageId)")
            }
        }

        val MIGRATION_4_5 = object : Migration(4, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE knowledge_documents ADD COLUMN sourceNoteId TEXT")
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS index_knowledge_documents_sourceNoteId " +
                        "ON knowledge_documents(sourceNoteId)",
                )
            }
        }

        val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "ALTER TABLE app_settings ADD COLUMN assistantNickname " +
                        "TEXT NOT NULL DEFAULT '一念无限'",
                )
            }
        }
    }
}

fun ProviderEntity.toDomain(apiKeyConfigured: Boolean) = ProviderConfig(
    id, name, baseUrl, ProviderProtocol.valueOf(protocol), apiKeyConfigured, createdAt, updatedAt,
)

fun ProviderConfig.toEntity() = ProviderEntity(id, name, baseUrl, protocol.name, createdAt, updatedAt)

fun ModelEntity.toDomain() = ModelProfile(
    id = id,
    providerId = providerId,
    remoteId = remoteId,
    displayName = displayName,
    maxOutputTokens = maxOutputTokens,
    isDefault = isDefault,
    visionStatus = VisionStatus.valueOf(visionStatus),
    visionCheckedAt = visionCheckedAt,
    createdAt = createdAt,
    updatedAt = updatedAt,
)

fun ModelProfile.toEntity() = ModelEntity(
    id, providerId, remoteId, displayName, maxOutputTokens, isDefault, visionStatus.name, visionCheckedAt, createdAt, updatedAt,
)

fun ConversationEntity.toDomain() = Conversation(
    id = id,
    title = title,
    titleAutoGenerated = titleAutoGenerated,
    model = if (modelMode == SettingMode.OVERRIDE.name) modelOverrideId else null,
    modelMode = SettingMode.valueOf(modelMode),
    thinkingEffort = thinkingEffort,
    systemPrompt = systemPrompt,
    systemPromptMode = SettingMode.valueOf(systemPromptMode),
    nickname = nickname,
    userAvatar = userAvatar,
    userAvatarMode = SettingMode.valueOf(userAvatarMode),
    assistantAvatar = assistantAvatar,
    assistantAvatarMode = SettingMode.valueOf(assistantAvatarMode),
    urlReaderBackend = urlReaderBackend?.let(UrlReaderBackend::valueOf),
    maxToolCalls = maxToolCalls,
    enableSearch = enableSearch,
    enableRead = enableRead,
    enableKnowledge = enableKnowledge,
    pinnedAt = pinnedAt,
    archivedAt = archivedAt,
    branchedFromConversationId = branchedFromConversationId,
    branchedFromMessageId = branchedFromMessageId,
    status = status,
    statusMessage = statusMessage,
    createdAt = createdAt,
    updatedAt = updatedAt,
    lastMessageAt = lastMessageAt,
)

fun Conversation.toEntity() = ConversationEntity(
    id = id,
    title = title,
    titleAutoGenerated = titleAutoGenerated,
    modelId = model,
    modelMode = modelMode.name,
    modelOverrideId = model.takeIf { modelMode == SettingMode.OVERRIDE },
    thinkingEffort = thinkingEffort,
    systemPrompt = systemPrompt,
    systemPromptMode = systemPromptMode.name,
    nickname = nickname,
    userAvatar = userAvatar,
    userAvatarMode = userAvatarMode.name,
    assistantAvatar = assistantAvatar,
    assistantAvatarMode = assistantAvatarMode.name,
    urlReaderBackend = urlReaderBackend?.name,
    maxToolCalls = maxToolCalls,
    enableSearch = enableSearch,
    enableRead = enableRead,
    enableKnowledge = enableKnowledge,
    pinnedAt = pinnedAt,
    archivedAt = archivedAt,
    branchedFromConversationId = branchedFromConversationId,
    branchedFromMessageId = branchedFromMessageId,
    status = status,
    statusMessage = statusMessage,
    createdAt = createdAt,
    updatedAt = updatedAt,
    lastMessageAt = lastMessageAt,
)

fun MessageEntity.toDomain() = ChatMessage(
    id, conversationId, parentMessageId, requestId, role, content, metadata, status, createdAt,
)

fun ChatMessage.toEntity() = MessageEntity(
    id, conversationId, parentMessageId, requestId, role, content, metadata, status, createdAt,
)

fun MessageAttachmentEntity.toDomain() = MessageAttachment(
    id, messageId, fileName, mimeType, AttachmentKind.valueOf(kind), storedPath, sizeBytes,
    extractedText, AttachmentStatus.valueOf(status), width, height, createdAt,
)

fun MessageAttachment.toEntity() = MessageAttachmentEntity(
    id, messageId, fileName, mimeType, kind.name, storedPath, sizeBytes, extractedText,
    status.name, width, height, createdAt,
)

fun NoteEntity.toDomain() = Note(id, title, body, sourceMessageId, sourceConversationId, createdAt, updatedAt)
fun Note.toEntity() = NoteEntity(id, title, body, sourceMessageId, sourceConversationId, createdAt, updatedAt)

fun AgentEntity.toDomain() = AgentProfile(
    id, name, description, modelId, systemPrompt, thinkingEffort, maxToolCalls,
    enableSearch, enableRead, enableKnowledge, createdAt, updatedAt,
)

fun AgentProfile.toEntity() = AgentEntity(
    id, name, description, modelId, systemPrompt, thinkingEffort, maxToolCalls,
    enableSearch, enableRead, enableKnowledge, createdAt, updatedAt,
)

fun KnowledgeDocumentEntity.toDomain() = KnowledgeDocument(
    id, name, mimeType, storedPath, sizeBytes, status, error, chunkCount, createdAt, updatedAt, sourceNoteId,
)

fun KnowledgeDocument.toEntity() = KnowledgeDocumentEntity(
    id, name, mimeType, storedPath, sizeBytes, status, error, chunkCount, createdAt, updatedAt, sourceNoteId,
)
