package xyz.mek030399.tokenflow.data

import java.io.IOException
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlin.math.roundToInt

const val DEFAULT_MODEL_MAX_OUTPUT_TOKENS = 16_384
const val MAX_MODEL_OUTPUT_TOKENS = 500_000

@Serializable
enum class ProviderProtocol {
    OPENAI_CHAT_COMPLETIONS,
    OPENAI_RESPONSES,
    ANTHROPIC_MESSAGES,
}

@Serializable
enum class UrlReaderBackend {
    BUILT_IN,
    INFOFLOW,
}

@Serializable
enum class SettingMode {
    INHERIT,
    OVERRIDE,
}

@Serializable
enum class VisionStatus { UNKNOWN, SUPPORTED, UNSUPPORTED }

@Serializable
enum class AttachmentKind { IMAGE, DOCUMENT }

@Serializable
enum class AttachmentStatus { READY, FAILED }

@Serializable
data class GlobalChatSettings(
    @SerialName("default_model_id") val defaultModelId: String? = null,
    @SerialName("system_prompt") val systemPrompt: String = "",
    @SerialName("user_avatar") val userAvatar: String = "U",
    @SerialName("assistant_avatar") val assistantAvatar: String = "AI",
    @SerialName("url_reader_backend") val urlReaderBackend: UrlReaderBackend = UrlReaderBackend.BUILT_IN,
    @SerialName("vision_fallback_model_id") val visionFallbackModelId: String? = null,
    @SerialName("mimo_tts_voice") val mimoTtsVoice: String = "mimo_default",
    @SerialName("mimo_tts_configured") val mimoTtsConfigured: Boolean = false,
)

data class EffectiveChatSettings(
    val modelId: String?,
    val systemPrompt: String,
    val userAvatar: String,
    val assistantAvatar: String,
    val urlReaderBackend: UrlReaderBackend,
    val thinkingEffort: String,
    val nickname: String,
    val maxToolCalls: Int,
)

@Serializable
data class ProviderConfig(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    @SerialName("base_url") val baseUrl: String,
    val protocol: ProviderProtocol,
    @SerialName("api_key_configured") val apiKeyConfigured: Boolean = false,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
)

data class ProviderDraft(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val baseUrl: String = "",
    val protocol: ProviderProtocol = ProviderProtocol.OPENAI_RESPONSES,
    val apiKey: String = "",
)

@Serializable
data class ModelProfile(
    val id: String = UUID.randomUUID().toString(),
    @SerialName("provider_id") val providerId: String,
    @SerialName("remote_id") val remoteId: String,
    @SerialName("display_name") val displayName: String = remoteId,
    @SerialName("max_output_tokens") val maxOutputTokens: Int = DEFAULT_MODEL_MAX_OUTPUT_TOKENS,
    @SerialName("is_default") val isDefault: Boolean = false,
    @SerialName("vision_status") val visionStatus: VisionStatus = VisionStatus.UNKNOWN,
    @SerialName("vision_checked_at") val visionCheckedAt: Long? = null,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
)

@Serializable
data class RemoteModel(val id: String, val displayName: String = id)

data class ProviderEditorData(
    val draft: ProviderDraft,
    val models: List<ModelProfile> = emptyList(),
)

@Serializable
data class Conversation(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",
    @SerialName("title_auto_generated") val titleAutoGenerated: Boolean = false,
    val model: String? = null,
    @SerialName("model_mode") val modelMode: SettingMode = SettingMode.INHERIT,
    @SerialName("thinking_effort") val thinkingEffort: String = "medium",
    @SerialName("system_prompt") val systemPrompt: String = "",
    @SerialName("system_prompt_mode") val systemPromptMode: SettingMode = SettingMode.INHERIT,
    val nickname: String = "",
    @SerialName("user_avatar") val userAvatar: String = "U",
    @SerialName("user_avatar_mode") val userAvatarMode: SettingMode = SettingMode.INHERIT,
    @SerialName("assistant_avatar") val assistantAvatar: String = "AI",
    @SerialName("assistant_avatar_mode") val assistantAvatarMode: SettingMode = SettingMode.INHERIT,
    @SerialName("url_reader_backend") val urlReaderBackend: UrlReaderBackend? = null,
    @SerialName("max_tool_calls") val maxToolCalls: Int = 7,
    @SerialName("enable_search") val enableSearch: Boolean = true,
    @SerialName("enable_read") val enableRead: Boolean = true,
    @SerialName("enable_knowledge") val enableKnowledge: Boolean = false,
    @SerialName("pinned_at") val pinnedAt: Long? = null,
    @SerialName("archived_at") val archivedAt: Long? = null,
    @SerialName("branched_from_conversation_id") val branchedFromConversationId: String? = null,
    @SerialName("branched_from_message_id") val branchedFromMessageId: String? = null,
    @SerialName("active_operation") val activeOperation: String = "",
    val status: String = "idle",
    @SerialName("status_message") val statusMessage: String = "",
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
    @SerialName("last_message_at") val lastMessageAt: Long? = null,
)

@Serializable
data class ChatMessage(
    val id: String = UUID.randomUUID().toString(),
    @SerialName("conversation_id") val conversationId: String,
    @SerialName("parent_message_id") val parentMessageId: String? = null,
    @SerialName("request_id") val requestId: String = "",
    val role: String,
    val content: String = "",
    val metadata: String = "",
    val status: String = "completed",
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
)

const val CONTEXT_BOUNDARY_ROLE = "context_boundary"

fun List<ChatMessage>.afterLatestContextBoundary(): List<ChatMessage> {
    val boundaryIndex = indexOfLast { it.role == CONTEXT_BOUNDARY_ROLE }
    return if (boundaryIndex < 0) this else drop(boundaryIndex + 1)
}

fun List<ChatMessage>.forModelContext(excludedMessageId: String? = null): List<ChatMessage> =
    afterLatestContextBoundary().filter { message ->
        message.id != excludedMessageId &&
            (message.role == "user" || (message.role == "assistant" && message.status == "completed"))
    }

fun List<ChatMessage>.latestAssistantInCurrentContext(): ChatMessage? =
    afterLatestContextBoundary().lastOrNull { it.role == "assistant" }

internal fun nextMessageCreatedAt(messages: List<ChatMessage>, currentTimeMillis: Long): Long {
    val latest = messages.maxOfOrNull(ChatMessage::createdAt) ?: return currentTimeMillis
    require(latest < Long.MAX_VALUE) { "Message timestamp is out of range" }
    return maxOf(currentTimeMillis, latest + 1)
}

data class WorkspaceSnapshot(
    val providers: List<ProviderConfig>,
    val models: List<ModelProfile>,
    val conversations: List<Conversation>,
    val exaConfigured: Boolean,
    val globalSettings: GlobalChatSettings = GlobalChatSettings(),
    val bookmarks: List<BookmarkedMessage> = emptyList(),
    val notes: List<Note> = emptyList(),
    val agents: List<AgentProfile> = emptyList(),
    val knowledgeDocuments: List<KnowledgeDocument> = emptyList(),
)

data class ConversationDetail(
    val conversation: Conversation,
    val messages: List<ChatMessage>,
    val attachments: List<MessageAttachment> = emptyList(),
)

data class ConversationWriteRequest(
    val title: String? = null,
    val model: String? = null,
    val modelMode: SettingMode? = null,
    val thinkingEffort: String? = null,
    val systemPrompt: String? = null,
    val systemPromptMode: SettingMode? = null,
    val nickname: String? = null,
    val userAvatar: String? = null,
    val userAvatarMode: SettingMode? = null,
    val assistantAvatar: String? = null,
    val assistantAvatarMode: SettingMode? = null,
    val urlReaderMode: SettingMode? = null,
    val urlReaderBackend: UrlReaderBackend? = null,
    val maxToolCalls: Int? = null,
    val enableSearch: Boolean? = null,
    val enableRead: Boolean? = null,
    val enableKnowledge: Boolean? = null,
    val pinnedAt: Long? = null,
    val archivedAt: Long? = null,
    val updatePinnedAt: Boolean = false,
    val updateArchivedAt: Boolean = false,
)

data class SendMessageRequest(
    val content: String = "",
    val enableSearch: Boolean,
    val enableRead: Boolean,
    val enableKnowledge: Boolean = false,
    val knowledgeChunkIds: List<Long> = emptyList(),
    val timeZone: String,
    val requestId: String,
    val attachments: List<PendingAttachment> = emptyList(),
)

data class PendingAttachment(
    val uri: String,
    val displayName: String,
    val mimeType: String = "application/octet-stream",
    val sizeBytes: Long = -1,
    val origin: PendingAttachmentOrigin = PendingAttachmentOrigin.PICKER,
    val appOwnedDraftPath: String? = null,
    val inlineText: String? = null,
)

enum class PendingAttachmentOrigin { PICKER, CAMERA, NOTE }

@Serializable
data class MessageAttachment(
    val id: String = UUID.randomUUID().toString(),
    @SerialName("message_id") val messageId: String,
    @SerialName("file_name") val fileName: String,
    @SerialName("mime_type") val mimeType: String,
    val kind: AttachmentKind,
    @SerialName("stored_path") val storedPath: String,
    @SerialName("size_bytes") val sizeBytes: Long,
    @SerialName("extracted_text") val extractedText: String = "",
    val status: AttachmentStatus = AttachmentStatus.READY,
    val width: Int? = null,
    val height: Int? = null,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
)

@Serializable
data class BookmarkedMessage(
    val id: String = UUID.randomUUID().toString(),
    @SerialName("message_id") val messageId: String,
    @SerialName("conversation_id") val conversationId: String,
    @SerialName("conversation_title") val conversationTitle: String = "",
    val content: String = "",
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
)

@Serializable
data class Note(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",
    val body: String = "",
    @SerialName("source_message_id") val sourceMessageId: String? = null,
    @SerialName("source_conversation_id") val sourceConversationId: String? = null,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
)

@Serializable
data class AgentProfile(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val description: String = "",
    @SerialName("model_id") val modelId: String? = null,
    @SerialName("system_prompt") val systemPrompt: String = "",
    @SerialName("thinking_effort") val thinkingEffort: String = "medium",
    @SerialName("max_tool_calls") val maxToolCalls: Int = 7,
    @SerialName("enable_search") val enableSearch: Boolean = true,
    @SerialName("enable_read") val enableRead: Boolean = true,
    @SerialName("enable_knowledge") val enableKnowledge: Boolean = false,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
)

@Serializable
data class KnowledgeDocument(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    @SerialName("mime_type") val mimeType: String,
    @SerialName("stored_path") val storedPath: String,
    @SerialName("size_bytes") val sizeBytes: Long,
    val status: String = "ready",
    val error: String = "",
    @SerialName("chunk_count") val chunkCount: Int = 0,
    @SerialName("created_at") val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at") val updatedAt: Long = System.currentTimeMillis(),
    @SerialName("source_note_id") val sourceNoteId: String? = null,
)

@Serializable
data class KnowledgeSnippet(
    val chunkId: Long,
    val documentId: String,
    val documentName: String,
    val position: Int,
    val text: String,
    val score: Int = 0,
)

@Serializable
data class KnowledgeCitation(
    @SerialName("chunk_id") val chunkId: Long,
    @SerialName("document_id") val documentId: String,
    @SerialName("document_name") val documentName: String,
    val position: Int,
) {
    val marker: String get() = "[[KB:$chunkId]]"
    val displayLabel: String get() = "$documentName · 片段 ${position + 1}"
}

data class KnowledgeImportSource(
    val uri: String,
    val displayName: String,
    val mimeType: String = "application/octet-stream",
    val sizeBytes: Long = -1,
)

@Serializable
data class UserMessageMetadata(
    @SerialName("knowledge_chunk_ids") val knowledgeChunkIds: List<Long> = emptyList(),
    @SerialName("vision_descriptions") val visionDescriptions: List<String> = emptyList(),
)

data class ToolOptions(
    val enableSearch: Boolean,
    val enableRead: Boolean,
    val enableKnowledge: Boolean = false,
    val urlReaderBackend: UrlReaderBackend = UrlReaderBackend.BUILT_IN,
)

data class UrlReadDiagnostic(
    val source: String,
    val finalUrl: String,
    val elapsedMs: Long,
    val success: Boolean,
    val detail: String,
)

data class Usage(
    val inputTokens: Long = 0,
    val outputTokens: Long = 0,
    val cacheReadTokens: Long = 0,
    val cacheCreationTokens: Long = 0,
    val cacheMetricsReported: Boolean = false,
) {
    val totalTokens: Long get() = (inputTokens + outputTokens).coerceAtLeast(0)
    val cacheHitPercentage: Int?
        get() = if (!cacheMetricsReported || inputTokens <= 0) null else
            (cacheReadTokens.coerceAtLeast(0).toDouble() * 100 / inputTokens)
                .roundToInt()
                .coerceIn(0, 100)

    operator fun plus(other: Usage) = Usage(
        inputTokens + other.inputTokens,
        outputTokens + other.outputTokens,
        cacheReadTokens + other.cacheReadTokens,
        cacheCreationTokens + other.cacheCreationTokens,
        cacheMetricsReported || other.cacheMetricsReported,
    )
}

@Serializable
data class ProcessEvent(
    val type: String = "status",
    val id: String = "",
    val name: String = "",
    val message: String = "",
    @SerialName("message_key") val messageKey: String = "",
    val attempt: Int = 0,
    @SerialName("max_attempts") val maxAttempts: Int = 0,
    val arguments: String = "",
    val result: String = "",
    val content: String = "",
    val ok: Boolean = true,
    @SerialName("knowledge_citations") val knowledgeCitations: List<KnowledgeCitation> = emptyList(),
)

@Serializable
data class AssistantMetadata(
    val events: List<ProcessEvent> = emptyList(),
    val usage: SerializableUsage = SerializableUsage(),
    @SerialName("usage_estimated") val usageEstimated: Boolean = false,
    @SerialName("completion_status") val completionStatus: String = "",
    val error: String = "",
    @SerialName("error_code") val errorCode: String = "",
    @SerialName("knowledge_citations") val knowledgeCitations: List<KnowledgeCitation> = emptyList(),
)

@Serializable
data class SerializableUsage(
    @SerialName("input_tokens") val inputTokens: Long = 0,
    @SerialName("output_tokens") val outputTokens: Long = 0,
    @SerialName("cache_read_tokens") val cacheReadTokens: Long = 0,
    @SerialName("cache_creation_tokens") val cacheCreationTokens: Long = 0,
    @SerialName("cache_metrics_reported") val cacheMetricsReported: Boolean = false,
) {
    fun toUsage() = Usage(
        inputTokens,
        outputTokens,
        cacheReadTokens,
        cacheCreationTokens,
        cacheMetricsReported || cacheReadTokens > 0 || cacheCreationTokens > 0,
    )
}

fun Usage.serializable() = SerializableUsage(
    inputTokens,
    outputTokens,
    cacheReadTokens,
    cacheCreationTokens,
    cacheMetricsReported,
)

fun ChatMessage.assistantMetadata(json: Json): AssistantMetadata {
    if (metadata.isBlank()) return AssistantMetadata()
    return runCatching { json.decodeFromString<AssistantMetadata>(metadata) }.getOrDefault(AssistantMetadata())
}

data class CanonicalToolCall(val id: String, val name: String, val arguments: String)

data class ProtocolReplayItem(
    val protocol: ProviderProtocol,
    val index: Int,
    val payload: JsonObject,
)

sealed interface CanonicalContentPart {
    data class Text(val text: String) : CanonicalContentPart
    data class Image(val mimeType: String, val base64: String) : CanonicalContentPart
    data class Document(val fileName: String, val text: String) : CanonicalContentPart
}

data class CanonicalMessage(
    val role: String,
    val content: String = "",
    val parts: List<CanonicalContentPart> = emptyList(),
    val toolCalls: List<CanonicalToolCall> = emptyList(),
    val toolCallId: String? = null,
    val toolName: String? = null,
    val replayItems: List<ProtocolReplayItem> = emptyList(),
)

fun CanonicalMessage.contentParts(): List<CanonicalContentPart> = if (parts.isNotEmpty()) parts else {
    if (content.isEmpty()) emptyList() else listOf(CanonicalContentPart.Text(content))
}

data class ModelCallRequest(
    val model: ModelProfile,
    val provider: ProviderConfig,
    val apiKey: String,
    val systemPrompt: String,
    val thinkingEffort: String,
    val messages: List<CanonicalMessage>,
    val tools: List<ToolDefinition>,
    val requestId: String,
    val maxOutputTokens: Int = model.maxOutputTokens,
)

data class ToolDefinition(
    val name: String,
    val description: String,
    val parameters: kotlinx.serialization.json.JsonObject,
)

sealed interface ModelStreamEvent {
    data class TextDelta(val content: String) : ModelStreamEvent
    data class ThinkingDelta(val content: String) : ModelStreamEvent
    data class ToolCallDelta(
        val index: Int,
        val id: String = "",
        val name: String = "",
        val arguments: String = "",
        val replaceArguments: Boolean = false,
    ) : ModelStreamEvent
    data class ReplayItem(val item: ProtocolReplayItem) : ModelStreamEvent
    data class TokenUsage(val usage: Usage) : ModelStreamEvent
    data object Completed : ModelStreamEvent
}

sealed interface ChatEvent {
    data class UserMessage(
        val message: ChatMessage,
        val attachments: List<MessageAttachment> = emptyList(),
    ) : ChatEvent
    data class AssistantMessage(val message: ChatMessage) : ChatEvent
    data class Delta(val content: String) : ChatEvent
    data class Process(val event: ProcessEvent) : ChatEvent
    data class Done(val usage: Usage, val autoTitle: Boolean) : ChatEvent
}

sealed interface EngineEvent {
    data class Delta(val content: String) : EngineEvent
    data class Process(val event: ProcessEvent) : EngineEvent
    data class Done(
        val content: String,
        val usage: Usage,
        val events: List<ProcessEvent>,
    ) : EngineEvent
}

data class ImportPreview(
    val payload: ConfigArchivePayload,
    val newProviders: Int,
    val updatedProviders: Int,
    val newModels: Int,
    val updatedModels: Int,
    val newAgents: Int = 0,
    val updatedAgents: Int = 0,
    val replacesExaKey: Boolean,
    val replacesMimoKey: Boolean = false,
    val replacesInfoFlowKey: Boolean = false,
    val conflicts: List<String> = emptyList(),
)

class ApiException(
    val status: Int,
    val code: String? = null,
    override val message: String,
    val retryable: Boolean = status == 429 || status in 500..599,
) : IOException(message)

class ConfigurationException(message: String) : IllegalArgumentException(message)

class NoteSummaryTooLongException(val maxCharacters: Int) :
    IllegalArgumentException("Note exceeds the $maxCharacters character summary limit")

class NoteChangedDuringSummaryException :
    IllegalStateException("The note changed while it was being summarized")
