package xyz.mek030399.tokenflow.data

import androidx.room.Room
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.async
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class ConversationConcurrencyRepositoryTest {
    @Test
    fun emptyLegacyModelOverrideCanBeCreatedButAnExplicitUnknownModelIsRejected() = runBlocking {
        withRepository(ConversationTestGateway { flow { emit(ModelStreamEvent.Completed) } }) { repository, _, _ ->
            val orphan = repository.createConversation(ConversationWriteRequest(modelMode = SettingMode.OVERRIDE))
            assertNull(orphan.model)
            assertEquals(SettingMode.OVERRIDE, orphan.modelMode)
            val failure = runCatching {
                repository.createConversation(ConversationWriteRequest(modelMode = SettingMode.OVERRIDE, model = "missing"))
            }.exceptionOrNull()
            assertTrue(failure is IllegalArgumentException)
        }
    }

    @Test
    fun lifecycleWritesPreserveEditsBeforeStreamingAndBeforeEveryTerminalState() = runBlocking {
        withTimeout(30_000) {
            for (terminal in listOf("completed", "failed", "interrupted")) {
                val streaming = CompletableDeferred<Unit>()
                val finish = CompletableDeferred<Unit>()
                val gateway = ConversationTestGateway {
                    flow {
                        emit(ModelStreamEvent.TextDelta("Partial response"))
                        streaming.complete(Unit)
                        finish.await()
                        if (terminal == "failed") error("Expected provider failure")
                        emit(ModelStreamEvent.Completed)
                    }
                }
                withRepository(gateway) { repository, dao, conversation ->
                    coroutineScope {
                        val generation = async {
                            runCatching {
                                repository.sendMessage(conversation.id, messageRequest()).collect { event ->
                                    if (event is ChatEvent.AssistantMessage) {
                                        repository.updateConversation(
                                            conversation.id,
                                            ConversationWriteRequest(title = "Edited before streaming"),
                                        )
                                    }
                                }
                            }
                        }
                        streaming.await()
                        assertEquals("Edited before streaming", dao.conversation(conversation.id)?.title)
                        assertEquals("generating", dao.conversation(conversation.id)?.status)
                        repository.updateConversation(
                            conversation.id,
                            ConversationWriteRequest(
                                title = "Edited during streaming",
                                enableSearch = true,
                                enableRead = true,
                                enableKnowledge = true,
                                maxToolCalls = 3,
                            ),
                        )
                        repository.setConversationPinned(conversation.id, true)
                        repository.setConversationArchived(conversation.id, true)
                        if (terminal == "interrupted") {
                            generation.cancelAndJoin()
                        } else {
                            finish.complete(Unit)
                            assertEquals(terminal == "completed", generation.await().isSuccess)
                        }
                        val stored = requireNotNull(dao.conversation(conversation.id))
                        assertEquals("Edited during streaming", stored.title)
                        assertFalse(stored.titleAutoGenerated)
                        assertNotNull(stored.pinnedAt)
                        assertNotNull(stored.archivedAt)
                        assertTrue(stored.enableSearch)
                        assertTrue(stored.enableRead)
                        assertTrue(stored.enableKnowledge)
                        assertEquals(3, stored.maxToolCalls)
                        assertEquals(if (terminal == "failed") "failed" else "idle", stored.status)
                        assertEquals(terminal, dao.messages(conversation.id).last().status)
                    }
                }
            }
        }
    }

    @Test
    fun delayedTitlePreservesManualRenameAndOtherSettings() = runBlocking {
        val started = CompletableDeferred<Unit>()
        val finish = CompletableDeferred<Unit>()
        withRepository(titleGateway(started, finish)) { repository, dao, conversation ->
            withTimeout(10_000) {
                coroutineScope {
                    putSourceMessage(dao, conversation.id)
                    val title = async { repository.generateTitle(conversation.id, force = true) }
                    started.await()
                    repository.updateConversation(conversation.id, ConversationWriteRequest(title = "Manual title"))
                    repository.setConversationPinned(conversation.id, true)
                    finish.complete(Unit)
                    val result = title.await()
                    assertEquals("Manual title", result.title)
                    assertFalse(result.titleAutoGenerated)
                    assertNotNull(result.pinnedAt)
                    assertEquals("Manual title", dao.conversation(conversation.id)?.title)
                }
            }
        }
    }

    @Test
    fun delayedTitleCannotRecreateDeletedConversation() = runBlocking {
        val started = CompletableDeferred<Unit>()
        val finish = CompletableDeferred<Unit>()
        withRepository(titleGateway(started, finish)) { repository, dao, conversation ->
            withTimeout(10_000) {
                coroutineScope {
                    putSourceMessage(dao, conversation.id)
                    val title = async { runCatching { repository.generateTitle(conversation.id, force = true) } }
                    started.await()
                    repository.deleteConversations(setOf(conversation.id))
                    finish.complete(Unit)
                    assertTrue(title.await().isFailure)
                    assertNull(dao.conversation(conversation.id))
                    assertTrue(dao.messages(conversation.id).isEmpty())
                }
            }
        }
    }

    @Test
    fun olderTitleCannotReplaceACompletedNewerTitle() = runBlocking {
        val oldStarted = CompletableDeferred<Unit>()
        val oldFinish = CompletableDeferred<Unit>()
        var calls = 0
        val gateway = ConversationTestGateway {
            flow {
                if (++calls == 1) {
                    oldStarted.complete(Unit)
                    oldFinish.await()
                    emit(ModelStreamEvent.TextDelta("Older title"))
                } else {
                    emit(ModelStreamEvent.TextDelta("Newer title"))
                }
                emit(ModelStreamEvent.Completed)
            }
        }
        withRepository(gateway) { repository, dao, conversation ->
            withTimeout(10_000) {
                coroutineScope {
                    putSourceMessage(dao, conversation.id)
                    val older = async { repository.generateTitle(conversation.id, force = true) }
                    oldStarted.await()
                    assertEquals("Newer title", repository.generateTitle(conversation.id, force = true).title)
                    oldFinish.complete(Unit)
                    assertEquals("Newer title", older.await().title)
                    assertEquals("Newer title", dao.conversation(conversation.id)?.title)
                }
            }
        }
    }

    private fun titleGateway(started: CompletableDeferred<Unit>, finish: CompletableDeferred<Unit>) =
        ConversationTestGateway {
            flow {
                started.complete(Unit)
                finish.await()
                emit(ModelStreamEvent.TextDelta("Generated title"))
                emit(ModelStreamEvent.Completed)
            }
        }

    private suspend fun putSourceMessage(dao: LocalDao, conversationId: String) {
        dao.putMessages(listOf(ChatMessage(conversationId = conversationId, role = "user", content = "Question").toEntity()))
    }

    private fun messageRequest() = SendMessageRequest(
        content = "Question",
        enableSearch = false,
        enableRead = false,
        timeZone = "UTC",
        requestId = "concurrency-request",
    )

    private suspend fun withRepository(
        gateway: ModelGateway,
        block: suspend (ChatRepository, LocalDao, Conversation) -> Unit,
    ) {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val database = Room.inMemoryDatabaseBuilder(context, TokenFlowDatabase::class.java).build()
        val dao = database.localDao()
        val secrets = SecretStore(context)
        val provider = ProviderConfig(
            name = "Concurrency fixture",
            baseUrl = "https://example.com/v1",
            protocol = ProviderProtocol.OPENAI_RESPONSES,
        )
        val model = ModelProfile(providerId = provider.id, remoteId = "fixture-model")
        val repository = ChatRepository(
            dao, secrets, gateway, DirectChatEngine(gateway, NoConversationTestTools), ConfigArchiveCodec(),
        )
        try {
            dao.putProvider(provider.toEntity())
            dao.putModels(listOf(model.toEntity()))
            secrets.write(secrets.providerKeyName(provider.id), "fixture-key")
            val conversation = repository.createConversation(
                ConversationWriteRequest(
                    title = "Original title",
                    model = model.id,
                    modelMode = SettingMode.OVERRIDE,
                    maxToolCalls = 0,
                    enableSearch = false,
                    enableRead = false,
                ),
            )
            block(repository, dao, conversation)
        } finally {
            secrets.remove(secrets.providerKeyName(provider.id))
            database.close()
        }
    }
}

private class ConversationTestGateway(
    private val response: (ModelCallRequest) -> Flow<ModelStreamEvent>,
) : ModelGateway() {
    override fun stream(request: ModelCallRequest) = response(request)
}

private object NoConversationTestTools : ToolRunner {
    override fun definitions(enableSearch: Boolean, enableRead: Boolean) = emptyList<ToolDefinition>()
    override suspend fun execute(call: CanonicalToolCall, enableSearch: Boolean, enableRead: Boolean) =
        ToolExecutionResult("{}", true)
}
