package xyz.mek030399.tokenflow.data

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test

class KnowledgeScopeAndroidTest {
    @get:Rule val migrations = MigrationTestHelper(InstrumentationRegistry.getInstrumentation(), TokenFlowDatabase::class.java)
    private val context get() = InstrumentationRegistry.getInstrumentation().targetContext

    @Test fun selectedRangeIsAppliedBeforeCandidateLimitAndAcrossManualAndToolRetrieval() = runBlocking {
        val database = Room.inMemoryDatabaseBuilder(context, TokenFlowDatabase::class.java).build()
        try {
            val dao = database.localDao()
            val excluded = addDocument(dao, "excluded", List(61) { "needle excluded passage $it" })
            val included = addDocument(dao, "included", listOf("needle included passage"))
            val scope = KnowledgeScope(KnowledgeScopeMode.SELECTED, listOf("included"))
            val store = KnowledgeStore(context, dao)
            assertEquals(included, store.search("needle", scope = scope).single().chunkId)
            assertEquals(listOf(included), store.snippets(listOf(excluded, included), scope).map(KnowledgeSnippet::chunkId))
            val executor = WebToolExecutor(SecretStore(context), ExaClient(), UrlReader(context), knowledgeStore = store)
            val call = CanonicalToolCall("scope-call", "search_knowledge", "{\"query\":\"needle\"}")
            val result = executor.execute(call, ToolOptions(enableSearch = false, enableRead = false, enableKnowledge = true, knowledgeScope = scope))
            assertTrue(result.ok)
            assertEquals(listOf("included"), result.citations.map(KnowledgeCitation::documentId))
            val none = KnowledgeScope(KnowledgeScopeMode.SELECTED)
            assertTrue(store.search("needle", scope = none).isEmpty())
            assertTrue(store.snippets(listOf(excluded, included), none).isEmpty())
            assertTrue(executor.execute(call, ToolOptions(enableSearch = false, enableRead = false, enableKnowledge = true, knowledgeScope = none)).citations.isEmpty())
        } finally {
            database.close()
        }
    }

    @Test fun migrationKeepsOriginalMessagesAndRejectsIncompatibleScopeColumn() {
        val name = "scope-v10-${System.nanoTime()}.db"
        val invalidName = "scope-invalid-v10-${System.nanoTime()}.db"
        try {
            migrations.createDatabase(name, 9).use { db ->
                db.execSQL("INSERT INTO conversations (id,title,titleAutoGenerated,thinkingEffort,systemPrompt,nickname,userAvatar,assistantAvatar,maxToolCalls,status,statusMessage,createdAt,updatedAt) VALUES ('retained-chat','Original conversation',0,'medium','','','U','AI',7,'idle','',1,1)")
                db.execSQL("INSERT INTO messages (id,conversationId,parentMessageId,requestId,role,content,metadata,status,createdAt) VALUES ('retained-message','retained-chat',NULL,'request','user','Original question','','completed',1)")
                db.execSQL("INSERT INTO knowledge_documents (id,name,mimeType,storedPath,sizeBytes,status,error,chunkCount,createdAt,updatedAt,sourceNoteId) VALUES ('retained','Original','text/plain','/private',10,'ready','',1,1,1,NULL)")
                db.execSQL("INSERT INTO knowledge_chunks (id,documentId,position,text,searchText) VALUES (1,'retained',0,'original contents','original contents')")
            }
            migrations.runMigrationsAndValidate(name, 10, true, TokenFlowDatabase.MIGRATION_9_10).use { db ->
                db.query("SELECT knowledgeScopeJson FROM conversations WHERE id='retained-chat'").use { cursor ->
                    assertTrue(cursor.moveToFirst())
                    assertEquals("{}", cursor.getString(0))
                }
                db.query("SELECT content FROM messages WHERE id='retained-message'").use { cursor ->
                    assertTrue(cursor.moveToFirst())
                    assertEquals("Original question", cursor.getString(0))
                }
                db.query("SELECT text FROM knowledge_chunks WHERE id=1").use { cursor ->
                    assertTrue(cursor.moveToFirst())
                    assertEquals("original contents", cursor.getString(0))
                }
                db.query("PRAGMA table_info(conversations)").use { cursor ->
                    var found = false
                    while (cursor.moveToNext()) if (cursor.getString(1) == "knowledgeScopeJson") {
                        found = true
                        assertEquals("'{}'", cursor.getString(4))
                    }
                    assertTrue(found)
                }
            }
            migrations.createDatabase(invalidName, 9).close()
            val incompatible = object : Migration(9, 10) {
                override fun migrate(db: SupportSQLiteDatabase) {
                    db.execSQL("ALTER TABLE conversations ADD COLUMN knowledgeScopeJson INTEGER NOT NULL DEFAULT 0")
                }
            }
            assertTrue(runCatching { migrations.runMigrationsAndValidate(invalidName, 10, true, incompatible).close() }.isFailure)
        } finally {
            context.deleteDatabase(name)
            context.deleteDatabase(invalidName)
        }
    }

    private suspend fun addDocument(dao: LocalDao, id: String, contents: List<String>): Long {
        dao.putKnowledgeDocument(KnowledgeDocumentEntity(id, id, "text/plain", "/private/$id", 1, "ready", "", contents.size, 1, 1))
        dao.replaceKnowledgeChunks(id, contents.mapIndexed { position, text -> KnowledgeChunkEntity(documentId = id, position = position, text = text, searchText = KnowledgeStore.searchable(text)) })
        return dao.knowledgeChunksForDocument(id).first().id
    }
}
